USE db_autogenerated;

SELECT postalZip AS 'Codigo Postal', region AS Region, country as 'Pais' FROM myTable;
SELECT * FROM myTable WHERE phone LIKE '(811)%';
-- UPDATE myTable SET country = 'Spain' WHERE country = 'Espanya';
SELECT * FROM myTable WHERE country = 'Italy' OR country = 'Spain';
SELECT COUNT(*) FROM myTable;
SELECT id, region, country, postalZip FROM myTable WHERE id IN (SELECT id FROM myTable WHERE country = 'Germany' OR country = 'Turkey');
SELECT MAX(id) FROM myTable;
SELECT MIN(id) FROM myTable;
SELECT COUNT(*), country FROM myTable GROUP BY country;
SELECT * FROM myTable ORDER BY postalZip LIMIT 10;
UPDATE myTable SET country = 'Espanya' WHERE country = 'Spain';
SELECT * FROM mytable WHERE country = 'Espanya';